/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-03-12 09:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class admin_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    ");
      msc.dao.MscDAO mdao = null;
      mdao = (msc.dao.MscDAO) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new msc.dao.MscDAO();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"image/mystyle1.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body >\r\n");
      out.write("  ");

request.setCharacterEncoding("utf-8");
String id=(String)session.getAttribute("id");
String name=(String)session.getAttribute("na");
String kind=(String)session.getAttribute("kind");
if(id!=null&&kind!="admin")
		{
int stunum=(int)mdao.CountStudent();
int teanum=(int)mdao.Countteacher();
int counum=(int)mdao.CountCourse();
 
      out.write("\r\n");
      out.write("    <table width=\"1024\" height=\"610\" bgcolor=\"#1fa0eb\" align=\"center\" cellspacing=\"0\" cellpadding=\"0\"><tr><td> \r\n");
      out.write("    <table width=\"1024\" height=\"610\" bgcolor=\"#ffffff\" align=\"center\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr><td>\r\n");
      out.write("    <table width=\"1016\" height=\"602\" bgcolor=\"#8dd8f8\" align=\"center\">\r\n");
      out.write("    <tr><td>\r\n");
      out.write("    <table align=\"center\">\r\n");
      out.write("    <tr><td width=\"724\" height=\"80\" style=\"FILTER: blur(direction=135,strength=8)\" align=\"center\"><i><font size=\"7\" face=\"华文行楷\" color=\"#2e0df7\">欢迎使用学生成绩管理系统！</font></i></td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    <tr><td><table background=\"image/tips.gif\" align=\"center\" width=\"598\" height=\"169\">\r\n");
      out.write("    <tr><td width=\"50\"></td><td height=\"59\"></td></tr>\r\n");
      out.write("    <tr ><td width=\"50\"></td><td height=\"20\" align=\"left\"><font color=\"#48f9f9\"><em><strong>欢迎你");
out.print(name); 
      out.write("</strong></em></font></td></tr>\r\n");
      out.write("    <tr><td width=\"50\"></td><td height=\"8\"></td></tr>\r\n");
      out.write("     <tr><td width=\"50\"></td><td height=\"50\"></td></tr>\r\n");
      out.write("    </table></td></tr>\r\n");
      out.write("     <tr><td height=\"50\"></td></tr>\r\n");
      out.write("    <tr><td>\r\n");
      out.write("    <table  bgcolor=\"#8dd8f8\" width=\"650\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"> \r\n");
      out.write("    <tr><th colspan=\"2\" height=\"25\" align=\"center\"><font  face=\"黑体\" color=\"#044a85\" size=\"5\">系统基本信息</font></th></tr>\r\n");
      out.write("    <tr align=\"center\"><td height=\"25\"><font size=\"4\" face=\"楷体\">当前系统中共有学生数：");
      out.print(stunum );
      out.write("</font></td><td width=\"80\" align=\"center\"><a href=\"admin_stu.jsp\"><img border=\"0\" src=\"image/scan.gif\"/></a></td></tr> \r\n");
      out.write("    <tr align=\"center\"><td height=\"25\"><font size=\"4\" face=\"楷体\">当前系统中共有教师数：");
      out.print(teanum );
      out.write("</font></td><td><a href=\"admin_tea.jsp\"><img border=\"0\" src=\"image/scan.gif\"/></a></td></tr> \r\n");
      out.write("\r\n");
      out.write("    <tr align=\"center\"><td height=\"25\"><font size=\"4\" face=\"楷体\">当前系统中共有课程数：");
      out.print(counum );
      out.write("</font></td><td><a href=\"admin_cou.jsp\"><img border=\"0\" src=\"image/scan.gif\"/></a></td></tr> \r\n");
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    <tr><td height=\"80\">&nbsp;</td></tr>\r\n");
      out.write("    </table></td></tr></table></td></tr></table>\r\n");
      out.write("    ");

		}
		else
		{
	
      out.write("\r\n");
      out.write("\t<div align=\"center\"> \r\n");
      out.write("\t<font size=\"5\" color=\"#ff0000\">非法登录！！！<br> \r\n");
      out.write("\t点<a target=\"_parent\" href=\"login.jsp\">这里</a>转到登陆页面！<br></font>\r\n");
      out.write("\t</div>");

		}
	
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
