/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-03-12 09:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class admin_005fnavi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/time.jsp", Long.valueOf(1505022761465L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"image/mystyle2.css\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("   ");

  request.setCharacterEncoding("utf-8");
  String id=(String)session.getAttribute("id");
  String kind=(String)session.getAttribute("kind");
 if(id!=null&&kind!="admin")
		{
	
      out.write("\r\n");
      out.write("    <table width=\"1024\"  align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr><td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"  bgcolor=\"#a1e3f9\">\r\n");
      out.write("    <tr><td width=\"1024\" height=\"110\" background=\"image/admin.jpg\" align=\"center\">\r\n");
      out.write("    <table><tr><td width=\"624\" height=\"85\" ></td><td></td></tr>\r\n");
      out.write("    <tr><td width=\"624\" ></td><td>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'time.jsp' starting page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"image/style1.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("<font face=\"Arial, Helvetica, Sans Serif\" size=\"2\" color=\"grey\" style=\"FILTER: blur(direction=135,strength=8)\"><b><i>\r\n");
      out.write("<span id=\"clock\">\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("var dayarray=new Array(\"星期天\",\"星期一\",\"星期二\",\"星期三\",\"星期四\",\"星期五\",\"星期六\")\r\n");
      out.write("var montharray=new Array(\"1月\",\"2月\",\"3月\",\"4月\",\"5月\",\"6月\",\"7月\",\"8月\",\"9月\",\"10月\",\"11月\",\"12月\")\r\n");
      out.write("function getthedate(){\r\n");
      out.write("var mydate=new Date()\r\n");
      out.write("var year=mydate.getYear()\r\n");
      out.write("if (year < 1000)\r\n");
      out.write("year+=1900\r\n");
      out.write("var day=mydate.getDay()\r\n");
      out.write("var month=mydate.getMonth()\r\n");
      out.write("var daym=mydate.getDate()\r\n");
      out.write("if (daym<10)\r\n");
      out.write("daym=\"0\"+daym\r\n");
      out.write("var hours=mydate.getHours()\r\n");
      out.write("var minutes=mydate.getMinutes()\r\n");
      out.write("var seconds=mydate.getSeconds()\r\n");
      out.write("var dn=\"AM\"\r\n");
      out.write("if (hours>=12)\r\n");
      out.write("dn=\"PM\"\r\n");
      out.write("if (hours>12){\r\n");
      out.write("hours=hours-12\r\n");
      out.write("}\r\n");
      out.write("{\r\n");
      out.write(" d = new Date();\r\n");
      out.write(" Time24H = new Date();\r\n");
      out.write(" Time24H.setTime(d.getTime() + (d.getTimezoneOffset()*60000) + 3600000);\r\n");
      out.write(" InternetTime = Math.round((Time24H.getHours()*60+Time24H.getMinutes()) / 1.44);\r\n");
      out.write(" if (InternetTime < 10) InternetTime = '00'+InternetTime;\r\n");
      out.write(" else if (InternetTime < 100) InternetTime = '0'+InternetTime;\r\n");
      out.write("}\r\n");
      out.write("if (hours==0)\r\n");
      out.write("hours=12\r\n");
      out.write("if (minutes<=9)\r\n");
      out.write("minutes=\"0\"+minutes\r\n");
      out.write("if (seconds<=9)\r\n");
      out.write("seconds=\"0\"+seconds\r\n");
      out.write("var cdate=year+\"年\"+montharray[month]+\"\"+daym+\"日    \"+dayarray[day]+\"   \"+hours+\":\"+minutes+\":\"+seconds+\"  \"+dn+\"\"\r\n");
      out.write("if (document.all)\r\n");
      out.write("document.all.clock.innerHTML=cdate\r\n");
      out.write("else if (document.getElementById)\r\n");
      out.write("document.getElementById(\"clock\").innerHTML=cdate\r\n");
      out.write("else\r\n");
      out.write("document.write(cdate)\r\n");
      out.write("}\r\n");
      out.write("if (!document.all && !document.getElementById)\r\n");
      out.write("getthedate()\r\n");
      out.write("function goforit(){\r\n");
      out.write("if (document.all||document.getElementById)\r\n");
      out.write("setInterval(\"getthedate()\",1000)\r\n");
      out.write("}\r\n");
      out.write("window.onload=goforit\r\n");
      out.write("</script>\r\n");
      out.write("</span>\r\n");
      out.write("</i></b></font>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("</td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    <tr><td>\r\n");
      out.write("    <table width=\"1024\"  height=\"20\"  align=\"center\">\r\n");
      out.write("\t<tr><td>\r\n");
      out.write("\t<div id=\"Whatever\">\r\n");
      out.write("\t<ul class=\"TabBarLevel1\" id=\"TabPage1\">\r\n");
      out.write("\t    <li id=\"Tab0\" class=\"Selected\"><a target=\"mainframe\" href=\"admin_main.jsp\" onclick=\"javascript:switchTab('TabPage1','Tab0');\">&nbsp;&nbsp;<strong> 首&nbsp;页</strong>&nbsp;&nbsp;</a></li>\r\n");
      out.write("\t\t<li id=\"Tab1\"><a target=\"mainframe\" href=\"admin_stu.jsp\" onclick=\"javascript:switchTab('TabPage1','Tab1');\">&nbsp; <strong>学 生 管 理</strong>&nbsp;</a></li>\r\n");
      out.write("\t\t<li id=\"Tab2\"><a target=\"mainframe\" href=\"admin_tea.jsp\" onclick=\"javascript:switchTab('TabPage1','Tab2');\">&nbsp; <strong>教 师 管 理</strong>&nbsp;</a></li>\r\n");
      out.write("\t\t<li id=\"Tab3\"><a target=\"mainframe\" href=\"admin_cou.jsp\" onclick=\"javascript:switchTab('TabPage1','Tab3');\">&nbsp; <strong>课 程 管 理</strong>&nbsp;</a></li>\r\n");
      out.write("\t\t<li id=\"Tab5\"><a target=\"mainframe\" href=\"admin_menu.jsp\" onclick=\"javascript:switchTab('TabPage1','Tab5');\">&nbsp;<strong>修 改 密 码</strong>&nbsp;</a></li>\r\n");
      out.write("\t\t<li id=\"Tab6\"><a target=\"_parent\" href=\"menu_slt?action=quit\" onclick=\"javascript:switchTab('TabPage1','Tab6');\">&nbsp;<strong>退 出</strong>&nbsp;</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script language=\"JavaScript\"> \r\n");
      out.write("//Switch Tab Effect\r\n");
      out.write("function switchTab(tabpage,tabid){\r\n");
      out.write("        var oItem = document.getElementById(tabpage);   \r\n");
      out.write("\tfor(var i=0;i<oItem.children.length;i++){\r\n");
      out.write("\t\tvar x = oItem.children(i);\t\r\n");
      out.write("\t\tx.className = \"\";\r\n");
      out.write("\t\tvar y = x.getElementsByTagName('a');\r\n");
      out.write("\t\ty[0].style.color=\"#333333\";\r\n");
      out.write("\t}\t\r\n");
      out.write("\tdocument.getElementById(tabid).className = \"Selected\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table></td></tr></table>\r\n");

		}
		else
		{
			response.setHeader("refresh","2;URL=login.jsp") ;
	
      out.write("\r\n");
      out.write("\t<div align=\"center\"> \r\n");
      out.write("\t<font size=\"5\" color=\"#ff0000\">非法登录！！！<br> \r\n");
      out.write("\t两秒后自动跳转到登陆窗口！！！<br></font>\r\n");
      out.write("\t</div>");

		}
	
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
