/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-03-12 09:21:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class admin_005fcou_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    \r\n");
      out.write("    <title></title>\r\n");
      out.write(" <SCRIPT Language=\"javascript\">\r\n");
      out.write(" <!--\r\n");
      out.write("  function isValid()\r\n");
      out.write("  {\t\r\n");
      out.write("  \tif(formaddcou.cno.value == \"\")\r\n");
      out.write("  \t{\t\r\n");
      out.write("  \t\twindow.alert(\"课序号不能为空！\"); \r\n");
      out.write(" \t\tdocument.formaddcou.elements(0).focus();\r\n");
      out.write("  \t\treturn  false;\r\n");
      out.write("  \t}\r\n");
      out.write("  \tif(formaddcou.cname.value == \"\")\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\twindow.alert(\"课程名不能为空！\");\r\n");
      out.write("  \t\tdocument.formaddcou.elements(1).focus();\r\n");
      out.write("  \t\treturn  false; \r\n");
      out.write("  \t}\r\n");
      out.write("  \tif(formaddcou.credit.value == \"\")\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\twindow.alert(\"课程学分称不能为空！\");\r\n");
      out.write("  \t\tdocument.formaddcou.elements(2).focus();\r\n");
      out.write("  \t\treturn  false; \r\n");
      out.write("  \t}\r\n");
      out.write("  \tformaddcou.submit();\r\n");
      out.write(" }\r\n");
      out.write("  -->\r\n");
      out.write("  </SCRIPT>\t\r\n");
      out.write("  <SCRIPT Language=\"javascript\">\r\n");
      out.write("  \r\n");
      out.write("   <script language=\"javascript\">\r\n");
      out.write("   function   shuru(txt){   \r\n");
      out.write("     if(isNaN(txt)){   \r\n");
      out.write("          window.alert(\"学分只能输入数字\"); \r\n");
      out.write("          document.formaddcou.elements(2).focus(); \r\n");
      out.write("          return  false;   \r\n");
      out.write("          }  \r\n");
      out.write("    }  \r\n");
      out.write("   </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body bgcolor=\"#8dd8f8\">\r\n");
      out.write("  <form name=\"formaddcou\" action=\"course_slt\" method=\"post\" onsubmit=\"return isValid(this);\"><div align=\"center\">\r\n");
      out.write("  <font size=\"5\" face=\"华文楷体\" color=\"#0000a0\"><strong>添加课程信息</strong></font></div>\r\n");
      out.write("  <br/><br/>\r\n");
      out.write("  <table border=\"1\" width=\"600\" height=\"120\" align=\"center\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr align=\"center\"><th colspan=\"2\" height=\"25\"><font size=\"4\" face=\"宋体\"><strong>请</strong></font><font size=\"4\" face=\"宋体\">输入课程信息</font></th></tr>\r\n");
      out.write("    <tr><td height=\"25\">课序号：</td><td><input type=\"text\" name=\"cno\"/></td></tr>\r\n");
      out.write("    <tr><th colspan=\"2\" height=\"15\"></th></tr>\r\n");
      out.write("    <tr><td height=\"25\">课程名称：</td><td><input type=\"text\" name=\"cname\"/></td></tr>\r\n");
      out.write("    <tr><th colspan=\"2\" height=\"15\"></th></tr>\r\n");
      out.write("    <tr><td height=\"25\">课程学分：</td><td><input type=\"text\" name=\"credit\" onchange=\"shuru(this.value )\"/></td></tr>\r\n");
      out.write("    <tr><th colspan=\"2\" height=\"15\"><input type=\"hidden\" name=\"action\" value=\"new\"></th></tr>\r\n");
      out.write("    <tr><td height=\"25\"><input type=\"reset\" value=\"重&nbsp&nbsp置\"/></td><td><input type=\"submit\" value=\"提&nbsp&nbsp交\"/></td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    <br/><br/><br/>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
