/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-05-11 02:38:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import msc.vo.*;

public final class admin_005ftea_005fupdrs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("msc.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()

+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    ");
      msc.dao.TeacherDAO tdao = null;
      tdao = (msc.dao.TeacherDAO) _jspx_page_context.getAttribute("tdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (tdao == null){
        tdao = new msc.dao.TeacherDAO();
        _jspx_page_context.setAttribute("tdao", tdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <SCRIPT Language=javascript>\r\n");
      out.write(" <!--\r\n");
      out.write("  function isValid()\r\n");
      out.write("  {\t\r\n");
      out.write("  \tif(formupdate.tname.value == \"\")\r\n");
      out.write("  \t{\t\r\n");
      out.write("  \t\twindow.alert(\"教师姓名为空！\"); \r\n");
      out.write(" \t\tdocument.formupdate.elements(0).focus();\r\n");
      out.write("  \t\treturn  false;\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tif(formupdate.tcode.value==\"\")\r\n");
      out.write("  \t{\r\n");
      out.write("  \t    window.alert(\"教师密码为空！\");\r\n");
      out.write("  \t    document.formupdate.elements(1).focus();\r\n");
      out.write("  \t    return  false;\r\n");
      out.write("  \t}\r\n");
      out.write("  \tformupdate.submit();\r\n");
      out.write(" }\r\n");
      out.write("  -->\r\n");
      out.write("  </SCRIPT>\t\t\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body bgcolor=\"#8dd8f8\">\r\n");
      out.write("    ");

    request.setCharacterEncoding("utf-8");
    String tid=request.getParameter("tid");
    Vector vector=tdao.Select(tid,"");
    int i=vector.size();
    Teacher tea[]=new Teacher[i];
    	
     
      out.write("\r\n");
      out.write("     <div align=\"center\"><font size=\"6\" color=\"#000080\" face=\"华文楷体\"><b><font size=\"5\">修改教师信息<br><br><br></font> \n");
      out.write(" \n");
      out.write("</b></font></div>\r\n");
      out.write("     <form name=\"formupdate\" action=\"teacher_slt\" method=\"post\" onsubmit=\"return isValid(this);\">\r\n");
      out.write("     <table width=\"650\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n");
      out.write("     <tr><th height=\"25\" colspan=\"2\"><input type=\"hidden\" name=\"action\" value=\"update\"/>请在下表输入\r\n");
      out.write("\r\n");
      out.write("修改后教师信息</th></tr>\r\n");
      out.write("\t");

	for(int j=0;j<i;j++){
	tea[j]=(Teacher)vector.elementAt(j);
	String rtid = tea[j].getTid() ;
	String rtname = tea[j].getTname() ;
    String rtcode=tea[j].getTcode();
	
      out.write("\r\n");
      out.write("\t<tr><td>教师工号：</td><td><input type=\"text\" name=\"tid\" value=\"");
      out.print(rtid);
      out.write("\" readonly/></td></tr>\r\n");
      out.write("\t<tr><th colspan=\"2\" height=\"15\"></th></tr>\r\n");
      out.write("\t<tr><td>教师姓名：</td><td><input type=\"text\" name=\"tname\" value=\"");
      out.print(rtname );
      out.write("\"/></td></tr>\r\n");
      out.write("\t<tr><th colspan=\"2\" height=\"15\"></th></tr>\r\n");
      out.write("\t<tr><td>教师密码：</td><td><input type=\"text\" name=\"tcode\" value=\"");
      out.print(rtcode );
      out.write("\"/></td></tr>\r\n");
      out.write("\t<tr><th colspan=\"2\" height=\"15\"></th></tr>\r\n");
      out.write("     <tr><td><input type=\"reset\" value=\"重  置\"/></td><td><input type=\"submit\" value=\"提  交\"/></td></tr>\r\n");
      out.write("\t");
 
	}
	if(i==0){	
	
      out.write("\r\n");
      out.write("\t<tr><th colspan=\"5\">无该教师信息！</th></tr>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      </table>\r\n");
      out.write("     </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
