/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-03-16 10:37:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import msc.vo.*;

public final class teacher_005fsub_005frs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("msc.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    ");
      msc.dao.ScDAO scdao = null;
      scdao = (msc.dao.ScDAO) _jspx_page_context.getAttribute("scdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (scdao == null){
        scdao = new msc.dao.ScDAO();
        _jspx_page_context.setAttribute("scdao", scdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    ");
      msc.dao.CourseDAO cdao = null;
      cdao = (msc.dao.CourseDAO) _jspx_page_context.getAttribute("cdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (cdao == null){
        cdao = new msc.dao.CourseDAO();
        _jspx_page_context.setAttribute("cdao", cdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    <title></title>\r\n");
      out.write("    ");

    request.setCharacterEncoding("utf-8");
    String cno=request.getParameter("cno");
    String tid=request.getParameter("tid");
    String con=request.getParameter("con");
    String xls=request.getParameter("xls");
    Vector all=new Vector();
    Vector course=new Vector();
    course=cdao.Select(cno,"",0);
    Course cou=new Course();
    if(course.size()!=0){
       cou=(Course)course.elementAt(0);
    }
    all=scdao.SelectStudent(cno,tid);
    int i=all.size();
    Sc stu[]=new Sc[i];
     
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <script language=\"javascript\">\r\n");
      out.write("   function   shuru(txt){   \r\n");
      out.write("     if(isNaN(txt)){   \r\n");
      out.write("          alert(\"请输入数字\");     \r\n");
      out.write("          }  \r\n");
      out.write("    }  \r\n");
      out.write("  </script>\r\n");
      out.write("  <body bgcolor=\"#8dd8f8\">\r\n");
      out.write("  ");
  
	if(xls.equals("yes")){
     String name = "download.xls";   
     name = new String(name.getBytes("utf-8"), "utf-8");   
     response.setHeader("Content-Disposition", "attachment; filename=" + name);   
     }
    
      out.write(" \r\n");
      out.write("  <div align=\"center\"><font size=\"4\" color=\"#000080\" face=\"华文楷体\"><b><font size=\"5\">");
      out.print(cou.getCname() );
      out.write("选课学生如下：</font></b></font></div>\r\n");
      out.write("     <form name=\"scoresub\" action=\"sc_slt?sn=");
      out.print(i );
      out.write("&tid=");
      out.print(tid );
      out.write("&cno=");
      out.print(cno );
      out.write("\" method=\"post\">\r\n");
      out.write("     <table border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n");
      out.write("     \r\n");
      out.write("     <tr align=\"center\"><td width=\"150\">学号</td><td width=\"150\">姓名</td><td width=\"150\">课程学分</td><td width=\"150\">平时成绩</td><td width=\"150\">期末成绩</td></tr>\r\n");
      out.write("\t");

	for(int j=0;j<i;j++){
	stu[j]=(Sc)all.elementAt(j);
	String sid = stu[j].getSid() ;
	String sname = stu[j].getSname() ;
    double credit=stu[j].getCredit();
    double pscore=stu[j].getPscore();
    double lscore=stu[j].getLscore();
	
      out.write("\r\n");
      out.write("            \t<tr align=\"center\">\r\n");
      out.write("\t\t    \t\t<td>");
      out.print(sid);
      out.write("</td>\r\n");
      out.write("\t\t    \t\t<td>");
      out.print(sname);
      out.write("</td>\r\n");
      out.write("\t\t       \t\t<td>");
      out.print(credit);
      out.write("</td>\r\n");
      out.write("\t\t       \t\t");
if(con.equals("subing")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"pscore");
      out.print(j );
      out.write("\" value=\"");
      out.print(pscore);
      out.write("\" onchange=\"shuru(this.value )\"/></td>\r\n");
      out.write("\t\t    \t\t<td><input type=\"text\" name=\"lscore");
      out.print(j );
      out.write("\" value=\"");
      out.print(lscore);
      out.write("\" onchange=\"shuru(this.value )\"/>\r\n");
      out.write("\t\t    \t\t<input type=\"hidden\" name=\"sid");
      out.print(j );
      out.write("\" value=\"");
      out.print(sid);
      out.write("\"/>\r\n");
      out.write("\t\t    \t\t</td>\r\n");
      out.write("\t\t    \t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t    \t\t<td>");
      out.print(pscore);
      out.write("</td>\r\n");
      out.write("\t\t    \t\t<td>");
      out.print(lscore);
      out.write("</td>\r\n");
      out.write("\t\t    \t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t");
 
	}
	if(i==0){	
	
      out.write("\r\n");
      out.write("\t<tr><th colspan=\"5\">无选课学生信息！</th></tr>\r\n");
      out.write("\t");
}
	else if(con.equals("subing")){
	 
      out.write("\r\n");
      out.write("\t <tr><th colspan=\"2\"><input type=\"reset\" value=\"重置\"/></th>\r\n");
      out.write("\t <th colspan=\"3\"><input type=\"submit\" name=\"submit\" value=\"暂时提交\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t <input type=\"submit\" name=\"submit\" value=\"最终提交\"/><input type=\"hidden\" name=\"action\" value=\"scoresub\"/></th></tr>\r\n");
      out.write("\t <tr><td colspan=\"8\"><div align=\"center\">\r\n");
      out.write("    <strong><font size=\"4\" color=\"#ff0000\">\t<font face=\"楷体\">提示：暂时提交后成绩可修改，最终提交后不可修改！\r\n");
      out.write("    </font></font></strong></div></td></tr>\r\n");
      out.write("\t ");
} 
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
